disable-require = true
#swarm-resource = "DOCKER_RESOURCE_GPU"
#accept-nvidia-visible-devices-envvar-when-unprivileged = true
#accept-nvidia-visible-devices-as-volume-mounts = true

[nvidia-container-cli]
#path = "/global/common/shared/das/podman/bin/nvidia-container-cli"
environment = []
# Disable to avoid collisions
#debug = "/tmp/nvidia-container-runtime.log"
#ldcache = "/etc/ld.so.cache"
load-kmods = false
no-cgroups = true
user = "root:root"
ldconfig = "@/sbin/ldconfig"

[nvidia-container-runtime]
# Disable to avoid collisions
#debug = "/tmp/nvidia-container-runtime.log"



