#!/bin/bash

# This does nothing
if [ $(echo $@|grep -c 'run --help') -gt 0 ] ; then
    mdir=$(dirname $0)
    cat $mdir/run_help.txt
elif [ $(echo $@|grep -c 'exec --help') -gt 0 ] ; then
    mdir=$(dirname $0)
    cat $mdir/exec_help.txt
elif [ $(echo $@|grep -c 'mksq ') -gt 0 ] ; then
    P=$(echo $@|sed 's/.*mksq -v //'|sed 's/:.*//')
    SQ=$(echo $@|sed 's|.*/sqout/||'|sed 's/ .*//')
    touch $P/$SQ
elif [ $(echo $@|grep -c 'run ') -gt 0 ] ; then
    echo "bogusid"
fi
echo $@ >> $MOCK_OUT
