name: Release Python Based RPM and Publish to PyPI
run-name: ${{ github.triggering_actor }} is packaging a release of ${{ github.event.repository.name }}
on: workflow_dispatch
    # push:
    #     tags:
    #       - 'v*' # push events matching e.g. v1, v2.1, v10.0.3

permissions:
  contents: read

jobs:
    publish-release:
        name: Publish Release
        runs-on: ubuntu-latest
        permissions:
          contents: write
          id-token: write
        steps:

        - name: Checkout code
          uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

        - name: Build Podman-HPC
          id: build_podman_hpc
          uses: ./.github/actions/build-podman-hpc

        - name: Publish package PyPI
          uses: pypa/gh-action-pypi-publish@81e9d935c883d0b210363ab89cf05f3894778450 #v1.8.14
          with:
            name: testpypi
            repository-url: https://test.pypi.org/legacy/

        - name: Release
          id: release
          uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 #v1
          with:
            generate_release_notes: true
            files: |
              ${{ steps.build_podman_hpc.outputs.python_dist }}/*
              ${{ steps.build_podman_hpc.outputs.srpm_dir }}/*
              ${{ steps.build_podman_hpc.outputs.rpm_dir }}/**/*
